name: Deploy

on: push

jobs:
  deploy: 
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: challenge
          entrypoint: https://deno.land/std/http/file_server.ts
          root: dist